### ISSUE TITLE
CLipboard Shortcut is not working

### ISSUE THREAD

**Issue by kwanice** [adirh3/Fluent-Search#105]
**Describe the bug**
when i press my shortcut to display the clipboard function, its not working, it just open a normal FS search

**To Reproduce**
1. settings
2. Clipboard
3. search hotkey

**Expected behavior**
be able to search only on the clipboard

**Desktop (please complete the following information):**
 - Windows 10 Version: 21390.1000
 - Fluent Search Version: 0.9.85.35

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.55

**Comment by Metroid-Prime** [comment]
@kwanice   please validate fix.

**Comment by kwanice** [comment]
@Metroid-Prime nope, still same

**Comment by kwanice** [comment]
on version 0.9.85.60 : the shorcut still not working, it open the simple FS search bar
@adirh3 @Metroid-Prime

**Comment by adirh3** [comment]
@kwanice Does it not open with the "clipboard" tag? or it does but you mean it doesn't show results when the search bar is minimal?

**Comment by kwanice** [comment]
@adirh3 
![image](https://user-images.githubusercontent.com/14847187/122509547-4326e080-d004-11eb-8369-3b6c6a50660e.png)

here the FS bar when i open with the shorcut for clipboard
when i do a research, its little bit different from a FS search normal, but it's not only clipboard (i think it's the purpose of the shorcut right?)

**Comment by adirh3** [comment]
@Nomad-0 Can you reproduce this?

**Comment by Nomad-0** [comment]
> @Nomad-0 Can you reproduce this?

yes. I set a hotkey for clipboard search, so If I press that hotkey, FS should open with clipboard tag on, but it opens just as normal FS

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.85.80

**Comment by Nomad-0** [comment]
yes, fixed on my end. @kwanice, please confirm

**Comment by Metroid-Prime** [comment]
Closing this as it's confirmed fixed by Nomad. @kwanice  if you're having the issue, please let us know and we can reopen

**Comment by kwanice** [comment]
@Metroid-Prime @Nomad-0 
its fixed :)
