### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by lvlzyro** [adirh3/Fluent-Search#664]
**Describe the bug**
The app is using very high CPU like 3-5%, it even goes up to 15 when I start to search.

**Screenshots**
On background:
![Screenshot 2022-08-19 172015](https://user-images.githubusercontent.com/45663782/185639252-c5215d94-07f8-4c3d-8f0d-39f183082198.png)

**Desktop (please complete the following information):**
 - Windows 11 Version: 22H2
 - Fluent Search Version 0.9.91.0

**Comment by adirh3** [comment]
@lvlzyro from the screenshot I suspect it is the file indexer, can you open Settings -> Files -> File indexer -> Change to Fluent Search indexer, click `Uninstall service` and then change back to Windows search.
Let me know if that helps

**Comment by lvlzyro** [comment]
I tried it, unfortunately didn't work. Any  other suggestions?

**Comment by adirh3** [comment]
@lvlzyro how many Fluent Search instances do you see in the Task manager?

**Comment by lvlzyro** [comment]
Just one

**Comment by adirh3** [comment]
@lvlzyro did you disable `Use GPU` in Settings -> System?
Also, would you mind trying to install the EXE version and see if it happens there? You can download it from here - https://fluentsearch.net

**Comment by lvlzyro** [comment]
Use GPU is enabled currently, but let me try to disable it. Then I'll try the exe install and then I'll tell you if it's fixed.

**Comment by lvlzyro** [comment]
I tried both, but it's sadly still the same.

**Comment by lvlzyro** [comment]
I tried both, it's still around 1% and peaks frequently.

**Comment by adirh3** [comment]
@lvlzyro thanks for testing, if gaming mode doesn't help than I don't have any other solution unfortunately.
I will be looking into it for the upcoming version.

**Comment by lvlzyro** [comment]
No problems, thanks for the help anyway!

**Comment by mofoni** [comment]
i had a similar problem.
Is "Screen" --> "Process Screen in background" enabled? 
If it is, you should disable it

**Comment by lvlzyro** [comment]
@mofoni i think it's disabled already. I guess all I can do is to wait @adirh3 to try and fix it.

**Comment by brian6932** [comment]
Not just high CPU usage, the indexer has far too much RAM consumption as well, the indexer def has a resource usage problem
![image](https://user-images.githubusercontent.com/18603393/189260896-d45442c8-44e1-4052-a866-42290311cbdd.png)

**Comment by adirh3** [comment]
@lvlzyro, can you please check if it's solved for you in the latest nightly version?

**Comment by adirh3** [comment]
> Same problem with me, unbelievably high ram usage, also can't open settings cause it keeps saying fluent search is still loading ![image](https://private-user-images.githubusercontent.com/73629408/359907441-fa872c45-3608-4f7b-b789-8f2258425e11.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyNDg0MjgsIm5iZiI6MTcyNDI0ODEyOCwicGF0aCI6Ii83MzYyOTQwOC8zNTk5MDc0NDEtZmE4NzJjNDUtMzYwOC00ZjdiLWI3ODktOGYyMjU4NDI1ZTExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIxVDEzNDg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgxNzNkZDJhNDhlYTA3MWI3ODVkYzU3ODUzYjk0MTQ0NTNhOTZmOTNmODZlNDY2YWNiZjFiZDQ1NTE1ZDVjNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.NS7ZkRDup-8ZOzH06bshK5bN5VBQXaw_GXEVh-FUW40)
> 
> Trying to end task in task manager is also not working, clicking on end task simply does nothing to fluent search @adirh3

Can you please check with the latest nightly? It should solve these issues.
You can download it from the GitHub main page - https://github.com/adirh3/Fluent-Search/issues

**Comment by thebluedev** [comment]
Yep, that fixes the RAM usage issues, I can search and stuff but can't access settings (fluent search is loading) as my customizations have reset
![image](https://github.com/user-attachments/assets/55f220a0-98d0-4a82-876b-0bfaaaa5ab24)

**Comment by thebluedev** [comment]
@adirh3 the latest nightly still doesn't work.

**Comment by adirh3** [comment]
> @adirh3 the latest nightly still doesn't work.

Can you please try to reset your settings  by going to `%appdata%\Blast\Settings` and rename that to `SettingsBackup`, then launching Fluent Search?

**Comment by thebluedev** [comment]
Problem still exists, I've also tried reinstalling and also deleting the
entire blast folder, still nothing

**Comment by adirh3** [comment]
> I encountered the same issue. I have tried using the latest stable version, but it still doesn't work.
> 
> Is this related to the file indexing? Because I couldn't open the settings anymore after adding the folders to exclude from the desktop today.
> 
> ![image](https://private-user-images.githubusercontent.com/107409303/399625818-9ac47f74-c013-4049-82c0-667382943860.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MDAyMjUsIm5iZiI6MTczNTc5OTkyNSwicGF0aCI6Ii8xMDc0MDkzMDMvMzk5NjI1ODE4LTlhYzQ3Zjc0LWMwMTMtNDA0OS04MmMwLTY2NzM4Mjk0Mzg2MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQwNjM4NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05NzA3YzNjNGNiNTNmMmJlMmE5NjI3MTljN2Q3YmExNWIzY2FiMDY4M2RiNDNkNjhjZjI5MzE3OTdkMjE1ZWNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.0k4LE_vpon1pPqJPVaw8oHl1vZz1G4yOqy0DxquNXbg)
> 
> Desktop: Windows 11 Version: 24H2 Fluent Search Version 1.0.0.68

This is background usage (not while searching)? How long was it above 10%?
This is most likely the indexer. Did you have a progress indicator (spinning ring) in Fluent Search when this happened?

Does it crash when you try to open settings? If so can you please look for errors in the Windows Event Viewer?

**Comment by adirh3** [comment]
> > This is background usage (not while searching)? How long was it above 10%?
> > This is most likely the indexer. Did you have a progress indicator (spinning ring) in Fluent Search when this happened?
> > Does it crash when you try to open settings? If so can you please look for errors in the Windows Event Viewer?
> 
> It kept going over 10% until I manually turned it off.
> 
> Indeed, there is a progress indicator (a spinning ring) in Fluent Search.
> 
> ![image](https://private-user-images.githubusercontent.com/107409303/399631061-d4696961-63b9-4d3c-b2fc-7675d666a13e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MDExNDUsIm5iZiI6MTczNTgwMDg0NSwicGF0aCI6Ii8xMDc0MDkzMDMvMzk5NjMxMDYxLWQ0Njk2OTYxLTYzYjktNGQzYy1iMmZjLTc2NzVkNjY2YTEzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQwNjU0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04OTkyOTgwYWFjNzFhZTQ2OWU0Y2JmZDc0YjM5MjUwNDlmMTg2ODRjY2Q5MWRiMWVkYzU5ODZkMmZhZTdkODMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.WlAlhdMxp8tgRt8eCiVJmizr7zZ5quuvwpTqGWIUGII)
> 
> However, I found that it functions normally when used in the Windows sandbox.
> 
> ![image](https://private-user-images.githubusercontent.com/107409303/399631374-6b7b682d-6201-42f1-8384-0dc6cf6337cf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU4MDExNDUsIm5iZiI6MTczNTgwMDg0NSwicGF0aCI6Ii8xMDc0MDkzMDMvMzk5NjMxMzc0LTZiN2I2ODJkLTYyMDEtNDJmMS04Mzg0LTBkYzZjZjYzMzdjZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwMlQwNjU0MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmNiODAzYjQ1MTViNmVmMDdjYzBmMGQwOWZkNWRiMTNkNGU3MmQyMjYzNDY1YzY4NTAzYzViZGUzNGRjNTE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cRthHXsP4bPW9o0fmn9vbGBgeLP-6pI_1WJmWnARZwQ)
> 
> If needed, I can provide my settings file.

Thanks for the info! Can you please send me your settings in a zip, in either [Discord](https://discord.gg/W2EuWvD6GD) or mail `support@fluentsearch.net`?
They are located at `%appdata%\Blast\Settings`
