### ISSUE TITLE
Impossibility to ignore a suggestion makes it impossible to use some tags

### ISSUE THREAD

**Issue by opack** [adirh3/Fluent-Search#670]
**Describe the bug**
I cannot use the tag `english` to get the Translator plugin to translate things in English. It's working properly in Japanese or French, but when I start typing `en`, there is a suggestion that remains even if I enter the full `english` word. Then, if I hit TAB, the suggestion is selected instead of the word `english`.

I would like to know how to enter my tag without accepting the suggestion, and/or how to remove this suggestion from the suggestions list, and/or how to disable suggestions.

**To Reproduce**
1. Open Fluent Search
2. Type `english` (of course if at this step Fluent Search makes no suggestion, you won't be able to reproduce)
3. Type TAB key
4. See the tag chosen to be the proposed one (which is, after all, what we would expect normally).

**Expected behavior**
Actually this behavior is normal, but I would love to be able to refuse/ignore a suggestion because in that particular case, the normal behavior becomes a bug.

**Screenshots**
![image](https://user-images.githubusercontent.com/3687098/186264768-8794224e-8ab3-44ec-ade1-266707965da2.png)

**Desktop (please complete the following information):**
 - Windows 10 Version: Windows 10 Professionnel 21H2
 - Fluent Search Version 0.9.91.9995

**Additional context**
I do not know where this selection come from 🤷‍♂️ I never ever visited this website (nor any `.cn` website, for that matter). I tried setting _Web > Web suggestion_ provider to `None` but it has no effect.

**Comment by adirh3** [comment]
@opack thanks for the input, I will improve this soon.
For now I suggest using `Ignored search tags` or `Map search tags` in Settings -> Search tags.
If you don't use that English tag, simply add it to the `Ignore search tag` and it should solve this specific issue.

**Comment by opack** [comment]
No no, that precisely the opposite: I do want to use it 😅 But I cannot because the suggestion get chosen instead of the simple `english` tag.

I already tried mapping `en` to `english`, but obviously the problem remains, as it also triggers the suggestion.
I also tried to use a mapping like `tren` (contraction from `translate english`), but look what it gets me 😅 
![image](https://user-images.githubusercontent.com/3687098/186268239-d1d25afe-951e-4975-90f3-0a6234f2954e.png)
I'm doomed 🤣

**Comment by opack** [comment]
OK, I understoog what you meant by ignoring the search tag: great feature by the way, with the help of the little light bulb I could ignored the bad tag:
![image](https://user-images.githubusercontent.com/3687098/186269567-0219470f-0425-4be6-8422-163e363f222b.png)

Now it is not suggested anymore. However, strangely, the `english` keyword does not trigger the Translator plugin. Should I open an issue in the Translator repository or is it related to the way the main program works?

When I type that:
![image](https://user-images.githubusercontent.com/3687098/186269765-ad60df89-d844-47a6-86d0-00d801f049e9.png)

Then hit TAB:
![image](https://user-images.githubusercontent.com/3687098/186269796-0a8727f2-d3cc-4896-8cfb-6faee247ca86.png)

Fluent uses the extension of the first result file as a tag, whereas I would like to do the same as that:
![image](https://user-images.githubusercontent.com/3687098/186269915-baabadee-1e5b-4789-b700-9e356dac80cb.png)
then
![image](https://user-images.githubusercontent.com/3687098/186269945-2ee54f64-d50e-4c26-95f5-b50b63d16793.png)

**Comment by adirh3** [comment]
@opack that's really interesting, somehow the English tag is somehow ignored.
Can you try to disable and enable the Translator search in Settings -> Translator?
That should reset the search tags, but I am not sure yet why this is happening.

If it's consistent for you, it would be helpful if you can send me your settings folder in Discord private message (they're in %appdata%/Blast/Settings)

**Comment by opack** [comment]
Nope, not working :-( I even tried to uninstall/reinstall the plugin, no luck. I'll contact you on Discord to send my settings 😉

**Comment by adirh3** [comment]
This issue has been potentially fixed in version 0.9.92.37                                         . Changelog - https://install.appcenter.ms/users/adirh3-gmail.com/apps/fluent-search-alpha/distribution_groups/exe

**Comment by opack** [comment]
Yeah! It works! 👍 

![image](https://user-images.githubusercontent.com/3687098/186992763-ad8adcd8-ff84-4d83-a02f-ab8e23201b49.png)

Thanks a lot for the quick and efficient fix! 👏
